stages:
  data_prep:
    cmd: python src/data_prep.py
    deps:
      - src/data_prep.py
      - data/raw/data.csv
    outs:
      - data/processed/train.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/train.csv
    outs:
      - models/risk_model.pkl

  monitor:
    cmd: python src/monitor.py
    deps:
      - src/monitor.py
      - models/risk_model.pkl
    outs:
      - metrics/monitoring_report.csv
